language: python
sudo: false
python:
    - "3.8"

arch:
    - amd64
    - arm64
env:
    - IPYTHON_INSTALL='pip install ipython' MPL_INSTALL='pip install matplotlib'
matrix:
    include:
        - python: "2.7"
          env: >
            IPYTHON_INSTALL='pip install ipython>=5,<6'
            MPL_INSTALL='pip install matplotlib'
        - python: "pypy"
          env: >
            IPYTHON_INSTALL='pip install ipython>=5,<6'
            MPL_INSTALL='echo "not installing matplotlib on pypy"'
        - python: "pypy3"
          env: >
            IPYTHON_INSTALL='pip install ipython'
            MPL_INSTALL='echo "not installing matplotlib on pypy"'
install:
    - pip install --upgrade pip
    - $IPYTHON_INSTALL
    - $MPL_INSTALL
    - pip install ipythonblocks
    - pip install .
    - pip install pytest-cov
    - pip install coveralls
script:
    - py.test --cov palettable --cov-report term-missing
after_success:
    - coveralls
